import { getCurrentLanguage, t } from "../../i18n/index.js";

interface ChannelWebConfigPageOptions {
  channelName: string;
  channelType?: string;
}

export function renderChannelWebConfigTestPage(
  options: ChannelWebConfigPageOptions,
): string {
  const bootstrap = JSON.stringify(options).replace(/</g, "\\u003c");
  const messages = JSON.stringify({
    title: t("TRAM Channel Config"),
    loadingTitle: t("Loading local config backend..."),
    loadingDescription: t("Waiting for metadata from the CLI-side server."),
    currentConfigInvalid: t("Current config is invalid."),
    noExtraFields: t("No extra fields"),
    selected: t("Selected"),
    qrBind: t("QR bind"),
    weChatQrBind: t("WeChat QR bind"),
    switchToWeChat:
      t(
        "Switch the channel type to WeChat to enable QR binding and saved account controls.",
      ),
    bindingStatus: t("Binding status"),
    openQrImage: t("Open QR image"),
    connectedUser: t("Connected user"),
    savedAccount: t("Saved account"),
    configured: t("Configured"),
    notConfigured: t("Not configured"),
    userId: t("User ID"),
    savedAt: t("Saved at"),
    startQrBinding: t("Start QR binding"),
    startQrBindingHelp: t(
      "The local CLI backend requests the QR code and continues polling the WeChat login API until it succeeds or fails.",
    ),
    weChatBaseUrl: t("WeChat Base URL"),
    startQrBindButton: t("Start QR Bind"),
    clearSavedLogin: t("Clear Saved Login"),
    heroBody: t(
      "A local browser harness for channel configuration. Save or delete will complete the CLI session after the response returns.",
    ),
    requestedType: t("Requested type"),
    selectedType: t("Selected Type"),
    existingConfig: t("Existing Config"),
    none: t("(none)"),
    chooseOne: t("(choose one)"),
    present: t("Present"),
    newChannel: t("New channel"),
    channelForm: t("Channel Form"),
    channelFormHelp: t(
      "Common TRAM channel settings plus adapter-specific fields derived from the channel registry.",
    ),
    saveAndExit: t("Save & Exit"),
    deleteChannel: t("Delete Channel"),
    weChatQrBinding: t("WeChat QR Binding"),
    weChatQrBindingHelp: t(
      "WeChat login is stored separately from the channel config, matching the existing CLI login behavior.",
    ),
    availableChannelTypes: t("Available Channel Types"),
    returnedByMetadata: t("Returned by the local metadata API."),
    currentRawConfig: t("Current Raw Config"),
    currentRawConfigHelp: t(
      "What is currently stored for this channel in user settings.",
    ),
    savingChannelConfig: t("Saving channel config..."),
    configSaved: t("Config saved. The CLI session will close automatically."),
    confirmDelete: t("Delete channel {{name}}?", { name: options.channelName }),
    deletingChannel: t("Deleting channel..."),
    channelDeleted: t(
      "Channel deleted. The CLI session will close automatically.",
    ),
    requestingWeChatQrCode: t("Requesting WeChat QR code..."),
    qrCodeRequested: t("QR code requested. Waiting for scan result..."),
    savedWeChatLoginCleared: t("Saved WeChat login cleared."),
    weChatConnected: t("WeChat account connected successfully."),
    weChatBindingFailed: t("WeChat binding failed."),
    mustBeNumber: t("must be a number."),
    mustBeValidJson: t("must be valid JSON"),
  }).replace(/</g, "\\u003c");
  const pageTitle = t("TRAM Channel Config").replace(/</g, "&lt;");
  const htmlLang = getCurrentLanguage();

  return [
    '<!doctype html>',
    `<html lang="${htmlLang}">`,
    '  <head>',
    '    <meta charset="utf-8" />',
    '    <meta name="viewport" content="width=device-width, initial-scale=1" />',
    `    <title>${pageTitle}</title>`,
    '    <style>',
    '      :root {',
    '        --bg: #f3ead9;',
    '        --panel: rgba(255, 249, 239, 0.94);',
    '        --panel-strong: #fffaf1;',
    '        --line: rgba(56, 43, 28, 0.14);',
    '        --text: #2f2418;',
    '        --muted: #756652;',
    '        --accent: #cf6c37;',
    '        --accent-strong: #a94f21;',
    '        --success: #2d7d55;',
    '        --danger: #b0423a;',
    '        --shadow: 0 24px 70px rgba(63, 41, 15, 0.14);',
    '      }',
    '      * { box-sizing: border-box; }',
    '      body {',
    '        margin: 0;',
    '        min-height: 100vh;',
    '        color: var(--text);',
    '        font-family: "Segoe UI", "PingFang SC", sans-serif;',
    '        background:',
    '          radial-gradient(circle at top left, rgba(207, 108, 55, 0.18), transparent 28%),',
    '          radial-gradient(circle at bottom right, rgba(45, 125, 85, 0.16), transparent 30%),',
    '          linear-gradient(135deg, #f8f0df 0%, #ecdfca 45%, #f6f1e8 100%);',
    '      }',
    '      .shell {',
    '        width: min(1180px, calc(100vw - 28px));',
    '        margin: 18px auto;',
    '        padding: 18px;',
    '        border-radius: 28px;',
    '        border: 1px solid var(--line);',
    '        background: var(--panel);',
    '        backdrop-filter: blur(14px);',
    '        box-shadow: var(--shadow);',
    '      }',
    '      .hero, .grid { display: grid; gap: 18px; }',
    '      .hero { grid-template-columns: 1.35fr 0.95fr; margin-bottom: 18px; }',
    '      .grid { grid-template-columns: 1.45fr 0.95fr; }',
    '      .stack { display: grid; gap: 18px; }',
    '      .card {',
    '        border-radius: 22px;',
    '        border: 1px solid var(--line);',
    '        background: var(--panel-strong);',
    '        padding: 20px;',
    '      }',
    '      .eyebrow {',
    '        display: inline-flex;',
    '        padding: 6px 12px;',
    '        border-radius: 999px;',
    '        background: rgba(207, 108, 55, 0.1);',
    '        color: var(--accent-strong);',
    '        font-size: 12px;',
    '        font-weight: 700;',
    '        text-transform: uppercase;',
    '        letter-spacing: 0.08em;',
    '      }',
    '      h1, h2, h3, p { margin: 0; }',
    '      h1 { margin-top: 14px; font-size: clamp(30px, 5vw, 50px); line-height: 0.94; letter-spacing: -0.05em; }',
    '      h2 { font-size: 20px; margin-bottom: 8px; }',
    '      .muted { color: var(--muted); line-height: 1.55; }',
    '      .metrics { display: grid; gap: 12px; }',
    '      .metric { border-radius: 16px; padding: 14px 16px; background: #f8f0e2; border: 1px solid var(--line); }',
    '      .metric-label { display: block; font-size: 12px; color: var(--muted); text-transform: uppercase; letter-spacing: 0.08em; margin-bottom: 6px; }',
    '      .metric-value { font-size: 17px; font-weight: 700; word-break: break-word; }',
    '      .field-grid { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 14px; }',
    '      .field.full { grid-column: 1 / -1; }',
    '      .field { display: grid; gap: 8px; }',
    '      label { font-size: 13px; font-weight: 700; }',
    '      .hint, .small { font-size: 12px; color: var(--muted); line-height: 1.45; }',
    '      input, select, textarea, button { font: inherit; }',
    '      input, select, textarea {',
    '        width: 100%;',
    '        border-radius: 14px;',
    '        border: 1px solid rgba(47, 36, 24, 0.16);',
    '        padding: 12px 14px;',
    '        background: white;',
    '        color: var(--text);',
    '      }',
    '      textarea { min-height: 116px; resize: vertical; }',
    '      input:focus, select:focus, textarea:focus { outline: none; border-color: rgba(207, 108, 55, 0.48); box-shadow: 0 0 0 3px rgba(207, 108, 55, 0.14); }',
    '      .actions { display: flex; gap: 12px; flex-wrap: wrap; margin-top: 18px; }',
    '      button { border: 0; border-radius: 999px; padding: 12px 18px; cursor: pointer; transition: transform 120ms ease, opacity 120ms ease; }',
    '      button:hover { transform: translateY(-1px); }',
    '      button:disabled { opacity: 0.6; cursor: progress; transform: none; }',
    '      .primary { background: var(--accent); color: white; font-weight: 700; }',
    '      .secondary { background: #efdfcf; color: var(--text); }',
    '      .danger { background: rgba(176, 66, 58, 0.12); color: var(--danger); font-weight: 700; }',
    '      .banner { margin-top: 16px; padding: 14px 16px; border-radius: 16px; border: 1px solid transparent; font-size: 14px; line-height: 1.5; }',
    '      .banner.info { background: rgba(207, 108, 55, 0.1); border-color: rgba(207, 108, 55, 0.16); }',
    '      .banner.success { background: rgba(45, 125, 85, 0.1); border-color: rgba(45, 125, 85, 0.16); color: var(--success); }',
    '      .banner.error { background: rgba(176, 66, 58, 0.1); border-color: rgba(176, 66, 58, 0.16); color: var(--danger); }',
    '      .list { display: grid; gap: 12px; }',
    '      .item { border-radius: 16px; padding: 14px 16px; background: #faf3e8; border: 1px solid var(--line); }',
    '      .tags { display: flex; gap: 8px; flex-wrap: wrap; margin-top: 8px; }',
    '      .tag { display: inline-flex; border-radius: 999px; padding: 6px 10px; background: rgba(47, 36, 24, 0.08); color: var(--muted); font-size: 12px; }',
    '      .mono { font-family: "Cascadia Code", Consolas, monospace; }',
    '      .qr { border-radius: 18px; padding: 16px; border: 1px dashed rgba(47, 36, 24, 0.18); background: #fbf5ec; display: grid; gap: 10px; }',
    '      .qr img { max-width: 240px; width: 100%; border-radius: 14px; border: 1px solid var(--line); }',
    '      a { color: var(--accent-strong); }',
    '      pre { margin: 0; white-space: pre-wrap; word-break: break-word; }',
    '      @media (max-width: 920px) {',
    '        .hero, .grid, .field-grid { grid-template-columns: 1fr; }',
    '        .shell { width: min(100vw - 14px, 1180px); margin: 7px auto; padding: 12px; }',
    '      }',
    '    </style>',
    '  </head>',
    '  <body>',
    '    <div class="shell">',
    '      <div id="app"></div>',
    '    </div>',
    '    <script>',
    '      const target = ' + bootstrap + ';',
    '      const text = ' + messages + ';',
    '      const root = document.getElementById("app");',
    '      const state = {',
    '        metadata: null,',
    '        draft: {},',
    '        busy: false,',
    '        message: "",',
    '        messageType: "info",',
    '        error: "",',
    '        binding: null,',
    '        bindingTimer: null,',
    '      };',
    '',
    '      function escapeHtml(value) {',
    '        return String(value)',
    '          .replace(/&/g, "&amp;")',
    '          .replace(/</g, "&lt;")',
    '          .replace(/>/g, "&gt;")',
    '          .replace(/"/g, "&quot;")',
    '          .replace(/\'/g, "&#39;");',
    '      }',
    '',
    '      async function api(path, options = {}) {',
    '        const response = await fetch(path, {',
    '          headers: {',
    '            "Content-Type": "application/json",',
    '            ...(options.headers || {}),',
    '          },',
    '          ...options,',
    '        });',
    '        let payload = null;',
    '        try {',
    '          payload = await response.json();',
    '        } catch {',
    '          payload = null;',
    '        }',
    '        if (!response.ok) {',
    '          throw new Error(payload?.error || `HTTP ${response.status}`);',
    '        }',
    '        return payload;',
    '      }',
    '',
    '      function dedupeFields(fields) {',
    '        const seen = new Set();',
    '        return fields.filter((field) => {',
    '          if (seen.has(field.key)) return false;',
    '          seen.add(field.key);',
    '          return true;',
    '        });',
    '      }',
    '',
    '      function getTypeDefinition(type) {',
    '        return state.metadata?.channelTypes?.find((item) => item.type === type) || null;',
    '      }',
    '',
    '      function currentFields() {',
    '        if (!state.metadata) return [];',
    '        const selectedType = state.draft.type || state.metadata.selectedType;',
    '        const typeDefinition = getTypeDefinition(selectedType);',
    '        return dedupeFields([',
    '          ...(state.metadata.commonFields || []),',
    '          ...((typeDefinition && typeDefinition.fields) || []),',
    '        ]);',
    '      }',
    '',
    '      function displayValue(field, value) {',
    '        if (value === undefined || value === null) {',
    '          if (field.defaultValue === undefined) return "";',
    '          value = field.defaultValue;',
    '        }',
    '        if (field.type === "json") return JSON.stringify(value ?? {}, null, 2);',
    '        if (field.type === "string-array") return Array.isArray(value) ? value.join("\\n") : "";',
    '        return String(value);',
    '      }',
    '',
    '      function initializeDraft(metadata, preserveExisting) {',
    '        const nextDraft = preserveExisting ? { ...state.draft } : {};',
    '        const currentConfig = metadata.current?.config || {};',
    '        const selectedType = nextDraft.type || metadata.selectedType || currentConfig.type || metadata.channelTypes?.[0]?.type || "";',
    '        nextDraft.type = selectedType;',
    '        const typeDefinition = metadata.channelTypes?.find((item) => item.type === selectedType) || null;',
    '        const fields = dedupeFields([',
    '          ...(metadata.commonFields || []),',
    '          ...((typeDefinition && typeDefinition.fields) || []),',
    '        ]);',
    '        for (const field of fields) {',
    '          if (!preserveExisting || nextDraft[field.key] === undefined) {',
    '            nextDraft[field.key] = displayValue(field, currentConfig[field.key]);',
    '          }',
    '        }',
    '        state.draft = nextDraft;',
    '      }',
    '',
    '      function parseDraftValue(field, rawValue) {',
    '        const text = typeof rawValue === "string" ? rawValue : "";',
    '        if (field.type === "number") {',
    '          if (text.trim() === "") return undefined;',
    '          const value = Number(text);',
    '          if (!Number.isFinite(value)) {',
    '            throw new Error(`${field.label} ${text.mustBeNumber}`);',
    '          }',
    '          return value;',
    '        }',
    '        if (field.type === "json") {',
    '          if (text.trim() === "") return field.defaultValue !== undefined ? field.defaultValue : undefined;',
    '          try {',
    '            return JSON.parse(text);',
    '          } catch (error) {',
    '            throw new Error(`${field.label} ${text.mustBeValidJson}: ${error.message}`);',
    '          }',
    '        }',
    '        if (field.type === "string-array") {',
    '          if (text.trim() === "") return [];',
    '          return text.split(/\\n|,/).map((item) => item.trim()).filter(Boolean);',
    '        }',
    '        const trimmed = text.trim();',
    '        return trimmed === "" ? undefined : trimmed;',
    '      }',
    '',
    '      function buildPayload() {',
    '        const config = {};',
    '        for (const field of currentFields()) {',
    '          const parsed = parseDraftValue(field, state.draft[field.key]);',
    '          if (parsed !== undefined) {',
    '            config[field.key] = parsed;',
    '          }',
    '        }',
    '        return config;',
    '      }',
    '',
    '      function bannerHtml() {',
    '        if (state.error) {',
    '          return `<div class="banner error">${escapeHtml(state.error)}</div>`;',
    '        }',
    '        if (!state.message) {',
    '          return "";',
    '        }',
    '        return `<div class="banner ${escapeHtml(state.messageType)}">${escapeHtml(state.message)}</div>`;',
    '      }',
    '',
    '      function validationHtml() {',
    '        const errors = state.metadata?.current?.validationErrors || [];',
    '        if (!errors.length) return "";',
    '        return `<div class="banner error"><strong>${escapeHtml(text.currentConfigInvalid)}</strong><br />${errors.map(escapeHtml).join("<br />")}</div>`;',
    '      }',
    '',
    '      function fieldHtml(field) {',
    '        const fullWidth = field.type === "json" || field.type === "string-array" || field.key === "instructions";',
    '        const value = escapeHtml(state.draft[field.key] ?? "");',
    '        const required = field.required ? " *" : "";',
    '        const hint = field.description ? `<div class="hint">${escapeHtml(field.description)}</div>` : "";',
    '        let control = "";',
    '        if (field.type === "enum") {',
    '          control = `<select data-field-key="${escapeHtml(field.key)}">${(field.options || []).map((option) => `<option value="${escapeHtml(option.value)}" ${String(state.draft[field.key] || "") === option.value ? "selected" : ""}>${escapeHtml(option.label)}</option>`).join("")}</select>`;',
    '        } else if (field.type === "json" || field.type === "string-array" || field.key === "instructions") {',
    '          control = `<textarea data-field-key="${escapeHtml(field.key)}">${value}</textarea>`;',
    '        } else {',
    '          const inputType = field.type === "number" ? "number" : field.type === "secret" ? "password" : "text";',
    '          control = `<input type="${inputType}" data-field-key="${escapeHtml(field.key)}" value="${value}" />`;',
    '        }',
    '        return `<div class="field ${fullWidth ? "full" : ""}"><label>${escapeHtml(field.label)}${required}</label>${control}${hint}</div>`;',
    '      }',
    '',
    '      function typeCardsHtml() {',
    '        const selectedType = state.draft.type || state.metadata?.selectedType;',
    '        return (state.metadata?.channelTypes || []).map((item) => {',
    '          const fieldTags = item.fields.length',
    '            ? item.fields.map((field) => `<span class="tag">${escapeHtml(field.key)}</span>`).join("")',
    '            : `<span class="tag">${escapeHtml(text.noExtraFields)}</span>`;',
    '          return `<div class="item"><div style="display:flex;justify-content:space-between;gap:12px;align-items:center;"><strong>${escapeHtml(item.displayName)}</strong>${selectedType === item.type ? `<span class="tag">${escapeHtml(text.selected)}</span>` : ""}</div><div class="small mono" style="margin-top:6px;">${escapeHtml(item.type)}</div><div class="tags">${fieldTags}${item.supportsQrBinding ? `<span class="tag">${escapeHtml(text.qrBind)}</span>` : ""}</div></div>`;',
    '        }).join("");',
    '      }',
    '',
    '      function bindingHtml() {',
    '        const selectedType = state.draft.type || state.metadata?.selectedType;',
    '        if (selectedType !== "weixin") {',
    '          return `<div class="item"><strong>${escapeHtml(text.weChatQrBind)}</strong><p class="small">${escapeHtml(text.switchToWeChat)}</p></div>`;',
    '        }',
    '        const account = state.metadata?.weixinAccount || { configured: false, baseUrl: "https://ilinkai.weixin.qq.com" };',
    '        const binding = state.binding;',
    '        const baseUrl = escapeHtml(state.draft.baseUrl || account.baseUrl || "https://ilinkai.weixin.qq.com");',
    '        const bindingBlock = binding ? `<div class="qr"><strong>${escapeHtml(text.bindingStatus)}: ${escapeHtml(binding.status)}</strong><div class="small">${escapeHtml(binding.message)}</div><div class="small mono">bindingId=${escapeHtml(binding.bindingId)}</div>${binding.qrCodeUrl ? `<a href="${escapeHtml(binding.qrCodeUrl)}" target="_blank" rel="noreferrer">${escapeHtml(text.openQrImage)}</a>` : ""}${binding.qrCodeUrl ? `<img src="${escapeHtml(binding.qrCodeUrl)}" alt="${escapeHtml(text.weChatQrBind)}" />` : ""}${binding.userId ? `<div class="small">${escapeHtml(text.connectedUser)}: <span class="mono">${escapeHtml(binding.userId)}</span></div>` : ""}</div>` : "";',
    '        return `<div class="stack"><div class="item"><strong>${escapeHtml(text.savedAccount)}</strong><div class="tags"><span class="tag">${account.configured ? escapeHtml(text.configured) : escapeHtml(text.notConfigured)}</span><span class="tag mono">${escapeHtml(account.baseUrl || "https://ilinkai.weixin.qq.com")}</span></div>${account.userId ? `<p class="small">${escapeHtml(text.userId)}: <span class="mono">${escapeHtml(account.userId)}</span></p>` : ""}${account.savedAt ? `<p class="small">${escapeHtml(text.savedAt)}: ${escapeHtml(account.savedAt)}</p>` : ""}</div><div class="item"><strong>${escapeHtml(text.startQrBinding)}</strong><p class="small">${escapeHtml(text.startQrBindingHelp)}</p><div class="field" style="margin-top:12px;"><label>${escapeHtml(text.weChatBaseUrl)}</label><input type="text" data-field-key="baseUrl" value="${baseUrl}" /></div><div class="actions"><button class="secondary" id="bindStartButton" ${state.busy ? "disabled" : ""}>${escapeHtml(text.startQrBindButton)}</button><button class="danger" id="clearWeixinButton" ${state.busy ? "disabled" : ""}>${escapeHtml(text.clearSavedLogin)}</button></div></div>${bindingBlock}</div>`;',
    '      }',
    '',
    '      function render() {',
    '        if (!state.metadata) {',
    '          root.innerHTML = `<div class="card"><div class="eyebrow">${escapeHtml(text.title)}</div><h1>${escapeHtml(text.loadingTitle)}</h1><p class="muted">${escapeHtml(text.loadingDescription)}</p></div>`;',
    '          return;',
    '        }',
    '        document.title = text.title;',
    '        root.innerHTML = `',
    '          <div class="hero">',
    '            <section class="card">',
    '              <div class="eyebrow">${escapeHtml(text.title)}</div>',
    '              <h1>${escapeHtml(state.metadata.channelName)}</h1>',
    '              <p class="muted">${escapeHtml(text.heroBody)}</p>',
    '              ${bannerHtml()}',
    '              ${validationHtml()}',
    '            </section>',
    '            <section class="card metrics">',
    '              <div class="metric"><span class="metric-label">${escapeHtml(text.requestedType)}</span><span class="metric-value mono">${escapeHtml(target.channelType || state.metadata.selectedType || text.none)}</span></div>',
    '              <div class="metric"><span class="metric-label">${escapeHtml(text.selectedType)}</span><span class="metric-value mono">${escapeHtml(state.draft.type || state.metadata.selectedType || text.chooseOne)}</span></div>',
    '              <div class="metric"><span class="metric-label">${escapeHtml(text.existingConfig)}</span><span class="metric-value">${state.metadata.current.exists ? escapeHtml(text.present) : escapeHtml(text.newChannel)}</span></div>',
    '            </section>',
    '          </div>',
    '          <div class="grid">',
    '            <div class="stack">',
    '              <section class="card">',
    '                <h2>${escapeHtml(text.channelForm)}</h2>',
    '                <p class="muted">${escapeHtml(text.channelFormHelp)}</p>',
    '                <div class="field-grid">${currentFields().map(fieldHtml).join("")}</div>',
    '                <div class="actions"><button class="primary" id="saveButton" ${state.busy ? "disabled" : ""}>${escapeHtml(text.saveAndExit)}</button><button class="danger" id="deleteButton" ${state.busy ? "disabled" : ""}>${escapeHtml(text.deleteChannel)}</button></div>',
    '              </section>',
    '              <section class="card">',
    '                <h2>${escapeHtml(text.weChatQrBinding)}</h2>',
    '                <p class="muted">${escapeHtml(text.weChatQrBindingHelp)}</p>',
    '                ${bindingHtml()}',
    '              </section>',
    '            </div>',
    '            <div class="stack">',
    '              <section class="card">',
    '                <h2>${escapeHtml(text.availableChannelTypes)}</h2>',
    '                <p class="muted">${escapeHtml(text.returnedByMetadata)}</p>',
    '                <div class="list">${typeCardsHtml()}</div>',
    '              </section>',
    '              <section class="card">',
    '                <h2>${escapeHtml(text.currentRawConfig)}</h2>',
    '                <p class="muted">${escapeHtml(text.currentRawConfigHelp)}</p>',
    '                <pre class="mono small">${escapeHtml(JSON.stringify(state.metadata.current.config, null, 2) || "null")}</pre>',
    '              </section>',
    '            </div>',
    '          </div>`;',
    '        wireEvents();',
    '      }',
    '',
    '      function wireEvents() {',
    '        const fieldMap = new Map(currentFields().map((field) => [field.key, field]));',
    '        document.querySelectorAll("[data-field-key]").forEach((element) => {',
    '          const key = element.getAttribute("data-field-key");',
    '          const field = fieldMap.get(key);',
    '          if (!field) return;',
    '          const eventName = element.tagName === "SELECT" ? "change" : "input";',
    '          element.addEventListener(eventName, (event) => {',
    '            state.draft[key] = event.target.value;',
    '            if (key === "type") {',
    '              const nextType = event.target.value;',
    '              const typeDefinition = getTypeDefinition(nextType);',
    '              for (const extraField of (typeDefinition?.fields || [])) {',
    '                if (state.draft[extraField.key] === undefined) {',
    '                  state.draft[extraField.key] = displayValue(extraField, undefined);',
    '                }',
    '              }',
    '              render();',
    '            }',
    '          });',
    '        });',
    '        document.getElementById("saveButton")?.addEventListener("click", saveChannel);',
    '        document.getElementById("deleteButton")?.addEventListener("click", deleteChannel);',
    '        document.getElementById("bindStartButton")?.addEventListener("click", startWeixinBind);',
    '        document.getElementById("clearWeixinButton")?.addEventListener("click", clearWeixinAccount);',
    '      }',
    '',
    '      async function loadMetadata(preserveDraft = false) {',
    '        state.busy = true;',
    '        state.error = "";',
    '        render();',
    '        try {',
    '          state.metadata = await api("/api/metadata");',
    '          initializeDraft(state.metadata, preserveDraft);',
    '          if (!preserveDraft) {',
    '            state.message = "";',
    '          }',
    '        } catch (error) {',
    '          state.error = error.message;',
    '        } finally {',
    '          state.busy = false;',
    '          render();',
    '        }',
    '      }',
    '',
    '      async function saveChannel() {',
    '        state.busy = true;',
    '        state.error = "";',
    '        state.message = text.savingChannelConfig;',
    '        state.messageType = "info";',
    '        render();',
    '        try {',
    '          await api("/api/channel", { method: "PUT", body: JSON.stringify({ config: buildPayload() }) });',
    '          state.message = text.configSaved;',
    '          state.messageType = "success";',
    '          render();',
    '        } catch (error) {',
    '          state.busy = false;',
    '          state.error = error.message;',
    '          render();',
    '        }',
    '      }',
    '',
    '      async function deleteChannel() {',
    '        if (!confirm(text.confirmDelete)) {',
    '          return;',
    '        }',
    '        state.busy = true;',
    '        state.error = "";',
    '        state.message = text.deletingChannel;',
    '        state.messageType = "info";',
    '        render();',
    '        try {',
    '          await api("/api/channel", { method: "DELETE" });',
    '          state.message = text.channelDeleted;',
    '          state.messageType = "success";',
    '          render();',
    '        } catch (error) {',
    '          state.busy = false;',
    '          state.error = error.message;',
    '          render();',
    '        }',
    '      }',
    '',
    '      async function startWeixinBind() {',
    '        state.busy = true;',
    '        state.error = "";',
    '        state.message = text.requestingWeChatQrCode;',
    '        state.messageType = "info";',
    '        render();',
    '        try {',
    '          const binding = await api("/api/weixin/bind", {',
    '            method: "POST",',
    '            body: JSON.stringify({ baseUrl: state.draft.baseUrl || undefined }),',
    '          });',
    '          state.binding = binding;',
    '          state.message = text.qrCodeRequested;',
    '          state.messageType = "info";',
    '          state.busy = false;',
    '          render();',
    '          pollBinding(binding.bindingId);',
    '        } catch (error) {',
    '          state.busy = false;',
    '          state.error = error.message;',
    '          render();',
    '        }',
    '      }',
    '',
    '      async function clearWeixinAccount() {',
    '        state.busy = true;',
    '        state.error = "";',
    '        render();',
    '        try {',
    '          await api("/api/weixin/account", { method: "DELETE" });',
    '          state.binding = null;',
    '          state.message = text.savedWeChatLoginCleared;',
    '          state.messageType = "success";',
    '          await loadMetadata(true);',
    '        } catch (error) {',
    '          state.busy = false;',
    '          state.error = error.message;',
    '          render();',
    '        }',
    '      }',
    '',
    '      async function pollBinding(bindingId) {',
    '        if (state.bindingTimer) {',
    '          clearTimeout(state.bindingTimer);',
    '          state.bindingTimer = null;',
    '        }',
    '        try {',
    '          const binding = await api("/api/weixin/bind?bindingId=" + encodeURIComponent(bindingId));',
    '          state.binding = binding;',
    '          render();',
    '          if (binding.status === "pending") {',
    '            state.bindingTimer = window.setTimeout(() => pollBinding(bindingId), 1500);',
    '            return;',
    '          }',
    '          if (binding.status === "connected") {',
    '            state.message = text.weChatConnected;',
    '            state.messageType = "success";',
    '            await loadMetadata(true);',
    '            return;',
    '          }',
    '          state.error = binding.error || binding.message || text.weChatBindingFailed;',
    '          render();',
    '        } catch (error) {',
    '          state.error = error.message;',
    '          render();',
    '        }',
    '      }',
    '',
    '      loadMetadata(false);',
    '    </script>',
    '  </body>',
    '</html>',
  ].join("\n");
}
